config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root 'users/sessions#new'
  end

  get 'sign_in', to: 'attendance_sign_in#new'
  get 'sign_out', to: 'attendance_sign_out#new'
  get 'pair_feedback', to: 'pair_feedbacks#new'
  get 'standup', to: 'static_pages#standup'
  get 'attendance', to: redirect('/')
  get 'student/sign_in', to: redirect('/')
  get 'companies/sign_in', to: redirect('/')
  get 'admins/sign_in', to: redirect('/')

  resources :otp, only: [:new, :create]

  devise_for :student, controllers: { invitations: 'invitations', registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  devise_for :admins, controllers: { omniauth_callbacks: 'omniauth_callbacks' }, skip: :registrations
  devise_for :companies, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }, skip: :invitations
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'omniauth_callbacks' }, skip: [:invitations, :registrations]

  resources :students, only: [:index, :edit, :update, :destroy] do
    resources :courses, only: [:index]
    resources :payments, only: [:index, :create]
    resources :attendance_records, only: [:index]
    resource :restore, only: [:update], to: 'student_restore#update'
    resource :add_course, only: [:update], to: 'add_course#update'
    resource :transcript, only: [:show]
    resource :certificate, only: [:show]
    resources :daily_submissions, only: [:index, :create]
    resources :peer_evaluations, only: [:index, :new, :create, :show]
    resources :pair_feedbacks, only: [:index]
    resource :probation, only: [:edit, :update]
    resources :checkins, only: [:create]
  end
  resources :admins, only: [:update]
  resources :payment_methods, only: [:index, :new]
  resources :bank_accounts, only: [:new, :create, :edit, :update]
  resource :credit_card, only: [:new, :create]
  resource :certificate, only: [:show]
  resource :transcript, only: [:show]
  resource :roster, only: [:show]
  resources :payments, only: [:update]
  resources :upfront_payments, only: [:create]
  resources :attendance_record_amendments, only: [:new, :create]
  resources :internships, only: [:index, :edit, :update]
  resources :cohorts, except: [:destroy] do
    resources :journals, only: [:index]
  end
  resources :courses, only: [:index, :show, :edit, :update] do
    resource :export, only: [:show], to: 'course_export#show'
    resources :code_reviews, except: [:destroy] do
      resource :report, only: [:show], to: 'code_review_reports#show'
    end
    resources :internships, only: [:show]
    resources :students, only: [:show]
    resources :day_attendance_records, only: [:index, :create]
    resources :ratings, only: [:index]
    resources :peer_evaluations, only: [:index]
    resource :daily_submissions, only: [:show]
    resource :meeting, only: [:new, :create]
    resources :checkins, only: [:index]
  end
  resources :ratings, only: [:create]
  resources :companies, only: [:show]

  resources :code_reviews, only: [:destroy] do
    resource :export, only: [:show], to: 'code_review_export#show'
    resources :submissions, only: [:index, :new, :create, :update]
    collection do
      patch :update_multiple, :path => ''
    end
  end

  resource :submissions, only: [:update]
  resources :submissions, only: [] do
    resources :reviews, only: [:new, :create, :update]
  end

  resources :journals, only: [:index]

  resources :stripe_callbacks, only: [:create]
  resources :payment_callbacks, only: [:create]
  resources :invitation_callbacks, only: [:create]
  resources :withdraw_callbacks, only: [:create]

  resources :signatures, only: [:create] do
    collection do
      resources :code_of_conduct, only: [:new, :create]
      resources :refund_policy, only: [:new, :create]
      resources :complaint_disclosure, only: [:new, :create]
      resources :enrollment_agreement, only: [:new, :create]
      resources :student_internship_agreement, only: [:new, :create]
    end
  end

  resource :code_review_copy, only: [:create]
  resource :random_pairs, only: [:show]
  resources :enrollments, only: [:create, :destroy]
  resource :sign_in, controller: 'attendance_sign_in', only: [:create]
  resource :sign_out, controller: 'attendance_sign_out', only: [:create]
  resource :course_internships, only: [:create, :destroy]
  resource :interview_assignments, only: [:destroy] do
    collection do
      post :create_multiple, path: ''
    end
    collection do
      patch :update_multiple, path: ''
    end
  end
  resources :internship_assignments, only: [:create, :destroy]

  resources :demographics, only: [:new, :create]

  resources :github_callbacks, only: [:create]

  resources :peer_evaluations, only: [:new]

  resource :pair_feedbacks, only: [:new, :create]

  resource :survey, only: [:new, :create]

  get 'reports', to: 'reports#index'
  resource :reports, only: [:index] do
    resources :teachers, only: [:index, :show]
  end

  patch '/courses/:course_id/code_reviews/:code_review_id/students/:student_id/code_review_visibility', to: 'code_review_visibilities#update', as: 'code_review_visibility'

  post :create_plaid_link_token, to: 'bank_accounts#create_plaid_link_token'
end

app/controllers/day_attendance_records_controller.rb
class DayAttendanceRecordsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @course = Course.find(params[:course_id])
    @day = Date.parse(params[:day]) if params[:day]
  end

  def create
    course = Course.find(params[:course_id])
    redirect_to course_day_attendance_records_path(course, day: params[:attendance_records][:day])
  end
end

app/views/day_attendance_records/index.html.erb
<h1>Attendance for <%= day_value.strftime("%A %B %d, %Y") %></h1>
<div class="panel panel-default">
  <div class="panel-body">
    <h4><%= @course.description %></h4>
    <h4><%= @course.teacher %></h4>

    <div class="form-group">
      <%= form_for :attendance_records, url: course_day_attendance_records_path(@course), html: { method: :post } do |f| %>
        <div class="row">
          <div class="col-md-4">
            <div class="input-group">
              <%= f.select :day, options_for_select(formatted_class_days, selected: day_value), {}, { class: 'form-control' } %>
              <span class="input-group-btn">
                <%= f.submit 'Change day', class: 'btn btn-info' %>
              </span>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="table-responsive">
      <table class="table table-hover datatable">
        <thead>
          <tr>
            <th>Student</th>
            <th>Status</th>
            <th>Signed in</th>
            <th>Signed out</th>
            <th>Pair</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @course.students.each do |student| %>
            <tr>
              <td class="col-md-3"><%= link_to student.name, course_student_path(@course, student) %></td>
              <td class="col-md-2 status-display">
                <% if !student.attendance_record_on_day(@day) %>
                  <span class="label label-primary">Absent</span>
                <% elsif student.attendance_record_on_day(@day).tardy && student.attendance_record_on_day(@day).left_early %>
                  <span class="label label-danger">Tardy</span>
                  <span class="label label-danger">Left early</span>
                <% elsif student.attendance_record_on_day(@day).tardy %>
                  <span class="label label-danger">Tardy</span>
                <% elsif student.attendance_record_on_day(@day).left_early %>
                  <span class="label label-danger">Left early</span>
                <% else %>
                  <span class="label label-success">On time</span>
                <% end %>
              </td>
              <td><%= student.attendance_record_on_day(@day).try(:created_at).try(:in_time_zone, @course.office.time_zone).try(:strftime, '%l:%M %p') %></td>
              <td><%= student.attendance_record_on_day(@day).try(:signed_out_time).try(:in_time_zone, @course.office.time_zone).try(:strftime, '%l:%M %p') %></td>
              <td>
                <% if @day.friday? || student.attendance_record_on_day(@day) == nil %>
                  -
                <% elsif student.pairs_on_day(@day).any? %>
                  <ul class='list-unstyled'>
                    <% student.pairs_on_day(@day).each do |pair| %>
                      <% if student.orphan_pairs_on_day(@day).include?(pair) %>
                        <li id='pair-name' class='text-danger'><strong><%= pair.name %></strong></li>
                      <% else %>
                        <li id='pair-name'><%= pair.name %></li>
                      <% end %>
                    <% end %>
                  </ul>
                <% else %>
                  <span class='text-danger'><strong>Solo</strong></span>
                <% end %>
              </td>
              <td>
                <%= form_for AttendanceRecordAmendment.new, remote: true do |f| %>
                  <%= f.select :status, options_for_select(["On time", "Tardy", "Left early", "Tardy and Left early", "Absent"], student.attendance_record_on_day(@day).try(:status) || 'Absent'), {}, {class: 'attendance-adjust', id: student.id} %>
                  <%= f.hidden_field :student_id, value: student.id %>
                  <%= f.hidden_field :date, value: @day %>
                  <% student.pairs_on_day(@day).each do |pair| %>
                    <%= hidden_field_tag "attendance_record_amendment[pair_ids][]", pair.id %>
                  <% end %>
                <% end %>
              </td>
              <td class="edit-attendance">
                <% if current_admin && can?(:manage, AttendanceRecord) %>
                  <%= link_to 'Edit', new_attendance_record_amendment_path(course: @course, student: student, day: @day, status: student.attendance_record_on_day(@day).try(:status)) %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/day_attendance_records/show.html.erb
<h1 class="page-header">Attendance by day</h1>

<%= form_for :attendance_records, url: cohort_attendance_statistics_path(@cohort), html: { method: :post } do |f| %>
  <%= f.select :day, options_for_select(formatted_class_days, selected: day_value), {}, { class: 'span3' } %>
  <p><%= f.submit 'Submit', class: 'btn btn-primary' %></p>
<% end %>

<h3>Attendance for <%= @day.strftime("%A %B %d, %Y") %></h3>
<hr>
<% @cohort.students.each do |student| %>
  <ul class="span12 unstyled">
      <li>
          <span class="span3"><%= link_to student.name, student, class: 'unstyled-link' %></span>
          <span>
            <% if !student.attendance_record_on_day(@day) %>
              <span class="btn btn-danger span3" disabled>Absent</span>
            <% elsif student.attendance_record_on_day(@day).tardy %>
              <span class="btn btn-warning span3" disabled>Tardy</span>
            <% elsif student.attendance_record_on_day(@day).left_early %>
              <span class="btn btn-warning span3" disabled>Left early</span>
            <% else %>
              <span class="btn btn-success span3" disabled>On time</span>
            <% end %>
          </span>
          <span class="span2">
            <%= link_to 'Edit', new_attendance_record_amendment_path(student: student, day: @day, attendance_statistics: true), class: 'unstyled-link'  %>
          </span>
          <span><%= student.pair_on_day(@day) ? student.pair_on_day(@day).name : 'Solo' %></span>
      </li>
  </ul>
<% end %>