config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root 'users/sessions#new'
  end

  get 'sign_in', to: 'attendance_sign_in#new'
  get 'sign_out', to: 'attendance_sign_out#new'
  get 'pair_feedback', to: 'pair_feedbacks#new'
  get 'standup', to: 'static_pages#standup'
  get 'attendance', to: redirect('/')
  get 'student/sign_in', to: redirect('/')
  get 'companies/sign_in', to: redirect('/')
  get 'admins/sign_in', to: redirect('/')

  resources :otp, only: [:new, :create]

  devise_for :student, controllers: { invitations: 'invitations', registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  devise_for :admins, controllers: { omniauth_callbacks: 'omniauth_callbacks' }, skip: :registrations
  devise_for :companies, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }, skip: :invitations
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'omniauth_callbacks' }, skip: [:invitations, :registrations]

  resources :students, only: [:index, :edit, :update, :destroy] do
    resources :courses, only: [:index]
    resources :payments, only: [:index, :create]
    resources :attendance_records, only: [:index]
    resource :restore, only: [:update], to: 'student_restore#update'
    resource :add_course, only: [:update], to: 'add_course#update'
    resource :transcript, only: [:show]
    resource :certificate, only: [:show]
    resources :daily_submissions, only: [:index, :create]
    resources :peer_evaluations, only: [:index, :new, :create, :show]
    resources :pair_feedbacks, only: [:index]
    resource :probation, only: [:edit, :update]
    resources :checkins, only: [:create]
  end
  resources :admins, only: [:update]
  resources :payment_methods, only: [:index, :new]
  resources :bank_accounts, only: [:new, :create, :edit, :update]
  resource :credit_card, only: [:new, :create]
  resource :certificate, only: [:show]
  resource :transcript, only: [:show]
  resource :roster, only: [:show]
  resources :payments, only: [:update]
  resources :upfront_payments, only: [:create]
  resources :attendance_record_amendments, only: [:new, :create]
  resources :internships, only: [:index, :edit, :update]
  resources :cohorts, except: [:destroy] do
    resources :journals, only: [:index]
  end
  resources :courses, only: [:index, :show, :edit, :update] do
    resource :export, only: [:show], to: 'course_export#show'
    resources :code_reviews, except: [:destroy] do
      resource :report, only: [:show], to: 'code_review_reports#show'
    end
    resources :internships, only: [:show]
    resources :students, only: [:show]
    resources :day_attendance_records, only: [:index, :create]
    resources :ratings, only: [:index]
    resources :peer_evaluations, only: [:index]
    resource :daily_submissions, only: [:show]
    resource :meeting, only: [:new, :create]
    resources :checkins, only: [:index]
  end
  resources :ratings, only: [:create]
  resources :companies, only: [:show]

  resources :code_reviews, only: [:destroy] do
    resource :export, only: [:show], to: 'code_review_export#show'
    resources :submissions, only: [:index, :new, :create, :update]
    collection do
      patch :update_multiple, :path => ''
    end
  end

  resource :submissions, only: [:update]
  resources :submissions, only: [] do
    resources :reviews, only: [:new, :create, :update]
  end

  resources :journals, only: [:index]

  resources :stripe_callbacks, only: [:create]
  resources :payment_callbacks, only: [:create]
  resources :invitation_callbacks, only: [:create]
  resources :withdraw_callbacks, only: [:create]

  resources :signatures, only: [:create] do
    collection do
      resources :code_of_conduct, only: [:new, :create]
      resources :refund_policy, only: [:new, :create]
      resources :complaint_disclosure, only: [:new, :create]
      resources :enrollment_agreement, only: [:new, :create]
      resources :student_internship_agreement, only: [:new, :create]
    end
  end

  resource :code_review_copy, only: [:create]
  resource :random_pairs, only: [:show]
  resources :enrollments, only: [:create, :destroy]
  resource :sign_in, controller: 'attendance_sign_in', only: [:create]
  resource :sign_out, controller: 'attendance_sign_out', only: [:create]
  resource :course_internships, only: [:create, :destroy]
  resource :interview_assignments, only: [:destroy] do
    collection do
      post :create_multiple, path: ''
    end
    collection do
      patch :update_multiple, path: ''
    end
  end
  resources :internship_assignments, only: [:create, :destroy]

  resources :demographics, only: [:new, :create]

  resources :github_callbacks, only: [:create]

  resources :peer_evaluations, only: [:new]

  resource :pair_feedbacks, only: [:new, :create]

  resource :survey, only: [:new, :create]

  get 'reports', to: 'reports#index'
  resource :reports, only: [:index] do
    resources :teachers, only: [:index, :show]
  end

  patch '/courses/:course_id/code_reviews/:code_review_id/students/:student_id/code_review_visibility', to: 'code_review_visibilities#update', as: 'code_review_visibility'

  post :create_plaid_link_token, to: 'bank_accounts#create_plaid_link_token'
end

app/models/peer_evaluation.rb
class PeerEvaluation < ApplicationRecord
  belongs_to :evaluator, class_name: :Student
  belongs_to :evaluatee, class_name: :Student
  has_many :peer_responses

  accepts_nested_attributes_for :peer_responses, allow_destroy: true
end

app/controllers/peer_evaluations_controller.rb
class PeerEvaluationsController < ApplicationController
  authorize_resource

  def index
    if params[:student_id]
      @student = Student.find(params[:student_id])
      authorize! :read, @student
    elsif params[:course_id]
      @course = Course.find(params[:course_id])
      authorize! :manage, @course
    end
  end

  def new
    @student = current_student
    @peer_evaluation = PeerEvaluation.new
    PeerQuestion.all.each { |q| @peer_evaluation.peer_responses.build(peer_question: q) }
    @options = PeerResponse::OPTIONS
    authorize! :read, @student
  end

  def create
    peer_evaluation = PeerEvaluation.new(peer_evaluation_params)
    if peer_evaluation.save
      redirect_to new_student_peer_evaluation_path(peer_evaluation.evaluator), notice: "Peer evaluation of #{peer_evaluation.evaluatee.name} submitted."
    else
      @student = current_student
      @peer_evaluation = peer_evaluation
      render :new
    end
  end

  def show
    @student = Student.find(params[:student_id])
    @peer_evaluation = PeerEvaluation.find(params[:id])
    @options = PeerResponse::OPTIONS
    authorize! :read, @student
    authorize! :read, @peer_evaluation
  end

private
  def peer_evaluation_params
    params.require(:peer_evaluation).permit(:evaluatee_id, peer_responses_attributes: [:peer_question_id, :response]).merge(evaluator_id: current_student.id)
  end
end

app/views/peer_evaluations/index.html.erb
<% content_for :title, 'Peer Evaluations' %>
<% if @student %>
  <% if current_student %>
    <p><%= link_to 'New peer evaluation', new_student_peer_evaluation_path(@student) %></p><br>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <h4>Peer evaluations written by <%= current_admin ? @student.name : 'you' %>:</h4>
          <div class="table-responsive">
            <table class="table">
              <tbody>
                <% @student.evaluations_of_peers.each do |eval| %>
                  <tr>
                    <td class="col-md-6">
                      <%= eval.created_at.to_date.strftime("%B %d %Y") %>
                    </td>
                    <td class="col-md-6"><%= link_to eval.evaluatee.name, student_peer_evaluation_path(@student, eval) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <h4>Peer evaluations of <%= current_admin ? @student.name : 'your whiteboarding' %>:</h4>
          <div class="table-responsive">
            <table class="table">
              <tbody>
                <% @student.evaluations_by_peers.each do |eval| %>
                  <tr>
                    <td class="col-md-6">
                      <%= eval.created_at.to_date.strftime("%B %d %Y") %>
                    </td>
                    <td class="col-md-6"><%= link_to 'click to view', student_peer_evaluation_path(@student, eval) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

<% elsif @course %>
  <h3>Peer evaluations by or of students in this course:</h3>
  <div class="row">
    <div class="col-md-6">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Evaluator</th>
              <th>Evaluatee</th>
            </tr>
          </thead>
          <tbody>
            <% @course.students.reorder(:name).each do |student| %>
              <tr>
                <td class="col-md-8">
                  <% if student.evaluations_of_peers.any? || student.evaluations_by_peers.any? %>
                    <%= link_to student.name, student_peer_evaluations_path(student) %>
                  <% else %>
                    <%= student.name %>
                  <% end %>
                </td>
                <td class="col-md-2"><%= student.evaluations_of_peers.count %></td>
                <td class="col-md-2"><%= student.evaluations_by_peers.count %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>

app/views/peer_evaluations/new.html.erb
<%= form_with model: [@student, @peer_evaluation] do |f| %>
  <%= render 'layouts/errors', object: @peer_evaluation %>

  <div class='form-group'>
    <%= f.label :evaluatee_id, 'Interviewee Name' %>
    <%= f.select :evaluatee_id, @student.course.students_all_locations.where.not(id: @student).order(:name).collect {|c| [ c.name, c.id ] }, { prompt: '-- please select --' }, { class: 'form-control', id: 'peer-eval-select-name', required: true } %>
  </div>

  <p>Interview the candidate using the following criteria. Meets expectations:</p>
  <ul>
    <li><strong>All of the time</strong>: The candidate always met these expectations. Great work!</li>
    <li><strong>Most of the time</strong>: The candidate met these expectations most of the time. Nice work, but there is room for improvement.</li>
    <li><strong>Some of the time</strong>: The candidate met these expectations some of the time. Further practice is recommended.</li>
    <li><strong>None of the time</strong>: The candidate did not need to meet the expectations and will need to redo the interview. Further practice is needed.</li>
  </ul>

  <h3>Technical</h3>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Did the interviewee:</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= f.nested_fields_for :peer_responses do |ff| %>
          <% if ff.object.peer_question.try(:category) == 'technical' %>
            <tr>
              <td class="col-md-8"><%= ff.object.peer_question.content %></td>
              <td>
                <%= ff.select :response, @options.collect, { prompt: '-- please select --' }, { class: 'form-control peer-eval-options', required: true } %>
                <%= ff.hidden_field :peer_question_id, value: ff.object.peer_question.id %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <h3>Professionalism</h3>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Did the interviewee:</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= f.nested_fields_for :peer_responses do |ff| %>
          <% if ff.object.peer_question.try(:category) == 'professionalism' %>
            <tr>
              <td class="col-md-8"><%= ff.object.peer_question.content %></td>
              <td>
                <%= ff.select :response, @options.collect, { prompt: '-- please select --' }, { class: 'form-control peer-eval-options', required: true } %>
                <%= ff.hidden_field :peer_question_id, value: ff.object.peer_question.id %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <h3>Feedback</h3>
  <div class="peer-feedback">
    <%= f.nested_fields_for :peer_responses do |ff| %>
      <% if ff.object.peer_question.try(:category) == 'feedback' %>
        <p><%= ff.object.peer_question.content %></p>
        <p><%= ff.text_area :response, rows: 10, required: true, class: 'form-control peer-feedback-comment' %></p>
        <%= ff.hidden_field :peer_question_id, value: ff.object.peer_question.id %>
      <% end %>
    <% end %>
  </div>

  <%= f.submit 'Submit peer evaluation', class: 'btn btn-success' %>
  <p>&nbsp;</p>
<% end %>

app/views/peer_evaluations/show.html.erb
<% if current_admin %>
  <p>Interviewer: <%= @peer_evaluation.evaluator.name %></p>
<% end %>
<p>Interviewee: <%= @peer_evaluation.evaluatee.name %></p>
<p>Date: <%= @peer_evaluation.created_at.to_date.strftime("%B %d %Y") %></p>

<h3>Technical</h3>
<div class="table-responsive">
  <table class="table">
    <tbody>
      <% @peer_evaluation.peer_responses.each do |response| %>
        <% if response.peer_question.try(:category) == 'technical' %>
          <tr>
            <td class="col-md-8"><%= response.peer_question.content %></td>
            <td><%= response.response %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<h3>Professionalism</h3>
<div class="table-responsive">
  <table class="table">
    <tbody>
      <% @peer_evaluation.peer_responses.each do |response| %>
        <% if response.peer_question.try(:category) == 'professionalism' %>
          <tr>
            <td class="col-md-8"><%= response.peer_question.content %></td>
            <td><%= response.response %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<h3>Feedback</h3>
<div class="peer-feedback">
  <table class="table">
    <% @peer_evaluation.peer_responses.each do |response| %>
      <% if response.peer_question.try(:category) == 'feedback' %>
        <tr><td>
          <p><%= response.peer_question.content %></p>
          <p><%= response.response %></p>
        </td></tr>
      <% end %>
    <% end %>
  </table>
</div>