config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root 'users/sessions#new'
  end

  get 'sign_in', to: 'attendance_sign_in#new'
  get 'sign_out', to: 'attendance_sign_out#new'
  get 'pair_feedback', to: 'pair_feedbacks#new'
  get 'standup', to: 'static_pages#standup'
  get 'attendance', to: redirect('/')
  get 'student/sign_in', to: redirect('/')
  get 'companies/sign_in', to: redirect('/')
  get 'admins/sign_in', to: redirect('/')

  resources :otp, only: [:new, :create]

  devise_for :student, controllers: { invitations: 'invitations', registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }
  devise_for :admins, controllers: { omniauth_callbacks: 'omniauth_callbacks' }, skip: :registrations
  devise_for :companies, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }, skip: :invitations
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'omniauth_callbacks' }, skip: [:invitations, :registrations]

  resources :students, only: [:index, :edit, :update, :destroy] do
    resources :courses, only: [:index]
    resources :payments, only: [:index, :create]
    resources :attendance_records, only: [:index]
    resource :restore, only: [:update], to: 'student_restore#update'
    resource :add_course, only: [:update], to: 'add_course#update'
    resource :transcript, only: [:show]
    resource :certificate, only: [:show]
    resources :daily_submissions, only: [:index, :create]
    resources :peer_evaluations, only: [:index, :new, :create, :show]
    resources :pair_feedbacks, only: [:index]
    resource :probation, only: [:edit, :update]
    resources :checkins, only: [:create]
  end
  resources :admins, only: [:update]
  resources :payment_methods, only: [:index, :new]
  resources :bank_accounts, only: [:new, :create, :edit, :update]
  resource :credit_card, only: [:new, :create]
  resource :certificate, only: [:show]
  resource :transcript, only: [:show]
  resource :roster, only: [:show]
  resources :payments, only: [:update]
  resources :upfront_payments, only: [:create]
  resources :attendance_record_amendments, only: [:new, :create]
  resources :internships, only: [:index, :edit, :update]
  resources :cohorts, except: [:destroy] do
    resources :journals, only: [:index]
  end
  resources :courses, only: [:index, :show, :edit, :update] do
    resource :export, only: [:show], to: 'course_export#show'
    resources :code_reviews, except: [:destroy] do
      resource :report, only: [:show], to: 'code_review_reports#show'
    end
    resources :internships, only: [:show]
    resources :students, only: [:show]
    resources :day_attendance_records, only: [:index, :create]
    resources :ratings, only: [:index]
    resources :peer_evaluations, only: [:index]
    resource :daily_submissions, only: [:show]
    resource :meeting, only: [:new, :create]
    resources :checkins, only: [:index]
  end
  resources :ratings, only: [:create]
  resources :companies, only: [:show]

  resources :code_reviews, only: [:destroy] do
    resource :export, only: [:show], to: 'code_review_export#show'
    resources :submissions, only: [:index, :new, :create, :update]
    collection do
      patch :update_multiple, :path => ''
    end
  end

  resource :submissions, only: [:update]
  resources :submissions, only: [] do
    resources :reviews, only: [:new, :create, :update]
  end

  resources :journals, only: [:index]

  resources :stripe_callbacks, only: [:create]
  resources :payment_callbacks, only: [:create]
  resources :invitation_callbacks, only: [:create]
  resources :withdraw_callbacks, only: [:create]

  resources :signatures, only: [:create] do
    collection do
      resources :code_of_conduct, only: [:new, :create]
      resources :refund_policy, only: [:new, :create]
      resources :complaint_disclosure, only: [:new, :create]
      resources :enrollment_agreement, only: [:new, :create]
      resources :student_internship_agreement, only: [:new, :create]
    end
  end

  resource :code_review_copy, only: [:create]
  resource :random_pairs, only: [:show]
  resources :enrollments, only: [:create, :destroy]
  resource :sign_in, controller: 'attendance_sign_in', only: [:create]
  resource :sign_out, controller: 'attendance_sign_out', only: [:create]
  resource :course_internships, only: [:create, :destroy]
  resource :interview_assignments, only: [:destroy] do
    collection do
      post :create_multiple, path: ''
    end
    collection do
      patch :update_multiple, path: ''
    end
  end
  resources :internship_assignments, only: [:create, :destroy]

  resources :demographics, only: [:new, :create]

  resources :github_callbacks, only: [:create]

  resources :peer_evaluations, only: [:new]

  resource :pair_feedbacks, only: [:new, :create]

  resource :survey, only: [:new, :create]

  get 'reports', to: 'reports#index'
  resource :reports, only: [:index] do
    resources :teachers, only: [:index, :show]
  end

  patch '/courses/:course_id/code_reviews/:code_review_id/students/:student_id/code_review_visibility', to: 'code_review_visibilities#update', as: 'code_review_visibility'

  post :create_plaid_link_token, to: 'bank_accounts#create_plaid_link_token'
end

app/models/survey.rb
class Survey
  include ActiveModel::Model

  attr_accessor :url

  def initialize(input:)
    munge_url(input)
    add_to_code_reviews
  end

private
  def munge_url(input)
    if input.include?('/')
      regex = /(?<=widget\.surveymonkey\.com\/collect\/website\/js\/)(.*\.js)/
      results = input.match(regex)
      self.url = results.present? ? results[0] : nil
    elsif input.include?('.js')
      self.url = input
    end
  end

  def add_to_code_reviews
    beginning_of_week = Time.zone.now.beginning_of_week
    end_of_week = beginning_of_week + 5.days
    courses = Course.current_courses.non_internship_courses
    CodeReview.where(course: courses).where('visible_date > ? AND visible_date < ?', beginning_of_week, end_of_week).each do |code_review|
      code_review.survey = url if self.url
      code_review.save(validate: false)
    end
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_admin!

  def create
    @survey = Survey.new(input: params[:url])
    @code_reviews = CodeReview.where(survey: @survey.url)
    if @survey.url && @code_reviews.any?
      :create
    elsif @survey.url.nil?
      redirect_to new_survey_path, alert: 'Invalid survey URL'
    elsif @code_reviews.empty?
      redirect_to new_survey_path, alert: 'No code reviews found with visible_date set to this week'
    end
  end
end

app/views/surveys/_survey.html.erb
<div class="well">
  <p>Let us know how you are doing by filling out the survey below. Your teacher will receive a summary of survey responses.</p>
  <%= fields_for :survey do |f| %>
    <% survey.questions.each do |question| %>
      <hr>
      <div class="form-group">
        <%= f.label :survey_question_id, "#{question.number}. #{question.content}" %>

        <ul class="list-unstyled">
          <%= f.fields_for :survey_options do |ff| %>
            <%= ff.collection_radio_buttons :survey_option_id, question.options, :id, :content do |b| %>
              <li><%= b.radio_button %> <%= b.label %></li>
            <% end %>
          <% end %>
        </ul>

      </div>
    <% end %>
  <% end %>
</div>

app/views/surveys/create.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p><strong>Survey <%= @survey.url %> is assigned to the following code reviews:</strong></p>
    <div class="table-responsive">
      <table class="survey-code-reviews-datatable table table-hover">
        <thead>
          <tr>
            <th>Code Review</th>
            <th>Office</th>
            <th>Course</th>
            <th>Visible Date</th>
            <th>Due Date</th>
          </tr>
        </thead>
        <tbody id="course-students">
          <% @code_reviews.each do |code_review| %>
            <tr>
              <td><%= link_to code_review.title, course_code_review_path(code_review.course, code_review) %></td>
              <td><%= code_review.course.office.name %></td>
              <td><%= code_review.course.description %></td>
              <td><%= code_review.visible_date.strftime('%b %-d') %></td>
              <td><%= code_review.due_date.strftime('%b %-d') %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/surveys/index.html.erb
<h1>Survey results for <%= @code_review.title %></h1>

app/views/surveys/new.html.erb
<div class="row">
  <%= form_tag survey_path do %>
    <%= render 'layouts/custom_errors', object: @survey %>
    <div class="well">
      <div class="form-group">
        <p>
          <strong>Survey URL for all code reviews <%= Time.zone.now.beginning_of_week.strftime('%b %-d') %> &ndash; <%= (Time.zone.now.beginning_of_week + 4.days).strftime('%b %-d') %>:</strong><br>
          <small>(copy/paste embed code from surveymonkey is fine)</small>
        </p>
        <%= text_area_tag 'url', nil, rows: 10, autofocus: true, class: 'form-control' %><br>
        <%= submit_tag "Add survey to this week's code reviews", class: 'btn btn-sm btn-info' %>
      </div>
    </div>
  <% end %>
</div>

app/views/surveys/show.html.erb
<%= form_for [@survey] do |f| %>
  <%= render @survey %>

<% end %>